import type { Config } from "tailwindcss";
import typography from "@tailwindcss/typography";

const config: Config = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        // Text colors
        "text-primary": "#171717",
        "text-primary-hover": "#0a0a0a",
        "text-primary-invert": "#fff",
        "text-secondary": "#525252",
        "text-tertiary": "#737373",
        "text-brand": "#4338ca",
        "text-disabled": "#a3a3a3",
        "text-error": "#dc2626",
        "text-error-emphasize": "#991b1b",
        "text-success": "#15803d",
        "text-warning": "#a16207",

        // Background colors
        "bg-primary": "#fff",
        "bg-primary-inverted": "#0a0a0a",
        "bg-primary-hover": "#fafafa",
        "bg-secondary": "#e5e7eb",
        "bg-secondary-hover": "#d1d5db",
        "bg-tertiary": "#fafafa",
        "bg-disabled": "#f5f5f5",
        "bg-disabled-emphasize": "#f3f4f6",
        "bg-brand-primary": "#4338ca",
        "bg-brand-primary-emphasize": "#3730a3",
        "bg-error": "#dc2626",
        "bg-error-emphasize": "#b91c1c",
        "bg-error-subtle": "#fef2f2",
        "bg-success-subtle": "#f0fdf4",
        "bg-brand-subtle": "#eef2ff",
        "bg-neutral-subtle": "#f9fafb",
        "bg-warning-subtle": "#fffbeb",

        // Line colors (border/rings)
        "line-primary": "#e5e5e5",
        "line-secondary": "#9ca3af",
        "line-success": "#bbf7d0",
        "line-brand-solid": "#4f46e5",
        "line-brand-subtle": "#c7d2fe",
        "line-error-subtle": "#fecaca",
        "line-warning-subtle": "#fde68a",

        // Icon colors
        "icon-emphasize": "#404040",
        "icon-primary": "#a3a3a3",
        "icon-primary-hover": "#737373",
        "icon-brand": "#6366f1",
        "icon-brand-background": "#eef2ff",
        "icon-success": "#15803d",
        "icon-error": "#dc2626",
        "icon-warning": "#facc15",

        // Input field, Form, Textarea colors
        "input-text-title": "#404040",
        "input-text-placeholder": "#737373",
        "input-text-hint": "#737373",
        "input-text-filled": "#171717",
        "input-text-disabled": "#a3a3a3",
        "input-text-error": "#dc2626",
        "input-background": "#fafafa",
        "input-border": "#e5e5e5",
      },
      // Create utility classes for your custom colors
      textColor: {
        primary: "#171717",
        "primary-hover": "#0a0a0a",
        "primary-invert": "#fff",
        secondary: "#525252",
        tertiary: "#737373",
        brand: "#4338ca",
        disabled: "#a3a3a3",
        error: "#dc2626",
        "error-emphasize": "#991b1b",
        success: "#15803d",
        warning: "#a16207",
        // Input field text colors
        "input-title": "#404040",
        "input-placeholder": "#737373",
        "input-hint": "#737373",
        "input-filled": "#171717",
        "input-disabled": "#a3a3a3",
        "input-error": "#dc2626",
      },
      backgroundColor: {
        primary: "#fff",
        "primary-inverted": "#0a0a0a",
        "primary-hover": "#fafafa",
        secondary: "#e5e7eb",
        "secondary-hover": "#d1d5db",
        tertiary: "#fafafa",
        disabled: "#f5f5f5",
        "disabled-emphasize": "#f3f4f6",
        "brand-primary": "#4338ca",
        "brand-primary-emphasize": "#3730a3",
        error: "#dc2626",
        "error-emphasize": "#b91c1c",
        "error-subtle": "#fef2f2",
        "success-subtle": "#f0fdf4",
        "brand-subtle": "#eef2ff",
        "neutral-subtle": "#f9fafb",
        "warning-subtle": "#fffbeb",
        input: "#fafafa",
      },
      borderColor: {
        primary: "#e5e5e5",
        secondary: "#9ca3af",
        success: "#bbf7d0",
        "brand-solid": "#4f46e5",
        "brand-subtle": "#c7d2fe",
        "error-subtle": "#fecaca",
        "warning-subtle": "#fde68a",
        input: "#e5e5e5",
      },
      ringColor: {
        primary: "#e5e5e5",
        secondary: "#9ca3af",
        success: "#bbf7d0",
        "brand-solid": "#4f46e5",
        "brand-subtle": "#c7d2fe",
        "error-subtle": "#fecaca",
        "warning-subtle": "#fde68a",
      },
      outlineColor: {
        primary: "#e5e5e5",
        secondary: "#9ca3af",
        success: "#bbf7d0",
        "brand-solid": "#4f46e5",
        "brand-subtle": "#c7d2fe",
        "error-subtle": "#fecaca",
        "warning-subtle": "#fde68a",
      },
    },
  },
  plugins: [typography],
};

export default config;
